name: flutter_nude_detector
description: Detect explicit content in images easily with flutter_nude_detector, a powerful Flutter package leveraging advanced machine learning for safer user experience.
version: 0.0.4+1
repository: https://github.com/piekarskipiotr/flutter-nude-detector

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_image_labeling: ^0.14.1
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  very_good_analysis: ">=3.1.0 <6.0.0"
